# Tugas 2


In [2]:
import numpy as np

No. 1

In [13]:
data = {
    'nik':'[1990022,2001077,2002019,2002081,2005099,2006003,2006104,2008160]',
    'nama':'["herman","badar","clara","rista","riani","afif","riven","endah"]',
    'jenis_kelamin':'["L","L","P","P","P","L","L","P"]',
    'alamat':'["tangerang","bekasi","depok","bogor","bekasi","karawang","tangerang","jakarta"]',
    'divisi':'["machinery","machinery","compressor","QC","QC","compressor","compressor","machinery"]',
    'jabatan':'["manager","staf","staf","staf","operator","operator","operator"]',
    'gaji':'[10000000,7500000,7000000,6500000,6000000,5500000,5500000,5000000]'
}

print(data)
type(data)

{'nik': '[1990022,2001077,2002019,2002081,2005099,2006003,2006104,2008160]', 'nama': '["herman","badar","clara","rista","riani","afif","riven","endah"]', 'jenis_kelamin': '["L","L","P","P","P","L","L","P"]', 'alamat': '["tangerang","bekasi","depok","bogor","bekasi","karawang","tangerang","jakarta"]', 'divisi': '["machinery","machinery","compressor","QC","QC","compressor","compressor","machinery"]', 'jabatan': '["manager","staf","staf","staf","operator","operator","operator"]', 'gaji': '[10000000,7500000,7000000,6500000,6000000,5500000,5500000,5000000]'}


dict

No. 2


In [3]:
satu = np.array([[1,2],
                 [4,5],
                 [7,8]]
                )
print(satu[2])

[7 8]


No. 3

In [4]:
dua = np.array([[1,6,9],
                 [2,5,8]]
                )
print(dua[:, 1])

[6 5]


No. 4

In [12]:
tiga = np.array([[4,3,8],
                 [7,2,5],
                 [6,1,9]]
                )
print(tiga[1:3, 1], '\n')
print(tiga[0, 1:3])

[2 1] 

[3 8]


No. 5

In [41]:
empat = np.array([[23,35,93,87],
                  [92,44,11,83],
                  [40,12,46,28],
                  [73,67,65,32]]
                )
print(empat[1, 1:4], '\n')
print(empat[2:4, 1:3], '\n')
print(empat[1:4, 1:4], '\n')
print(empat[1:3, 0:2], '\n')
print(empat[0:2, 0:3], '\n')
print(empat[1:4, 1], '\n')

[44 11 83] 

[[12 46]
 [67 65]] 

[[44 11 83]
 [12 46 28]
 [67 65 32]] 

[[92 44]
 [40 12]] 

[[23 35 93]
 [92 44 11]] 

[44 12 67] 

